spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

datasource:
  master:
    url: jdbc:mysql://localhost:3306/greek_course?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: yuyibing
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  slave1:
    url: jdbc:mysql://localhost:3316/greek_course?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: yuyibing
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  slave2:
    url: jdbc:mysql://localhost:3316/greek_course?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver



